;;; eudic-test.el --- Lookup and studylist tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'eudic-studylist)

(ert-deftest eudic-lookup-encodes-both-url-schemes ()
  (let ((eudic-auto-add-to-studylist nil)
        urls)
    (let ((eudic-open-url-function (lambda (url) (push url urls))))
      (eudic-lookup "  hello world/?#&  ")
      (eudic-lookup-in-popup " café 中文 "))
    (should (equal (nreverse urls)
                   '("eudic://dict/hello%20world%2F%3F%23%26"
                     "eudic://lp-dict/caf%C3%A9%20%E4%B8%AD%E6%96%87")))))

(ert-deftest eudic-lookup-rejects-empty-input-before-side-effects ()
  (let ((eudic-auto-add-to-studylist t)
        (eudic-open-url-function (lambda (_) (ert-fail "Opened empty lookup"))))
    (cl-letf (((symbol-function 'eudic--auto-add-word-to-studylist)
               (lambda (_) (ert-fail "Saved empty word"))))
      (dolist (word '(nil "" " \n\t "))
        (should-error (eudic-lookup word) :type 'user-error)
        (should-error (eudic-lookup-in-popup word) :type 'user-error)))))

(ert-deftest eudic-lookup-interactive-input ()
  (let ((eudic-auto-add-to-studylist nil)
        urls)
    (let ((eudic-open-url-function (lambda (url) (push url urls))))
      (with-temp-buffer
        (insert "hello world")
        (goto-char 3)
        (call-interactively #'eudic-lookup)
        (let ((transient-mark-mode t))
          (goto-char (point-max))
          (set-mark (point-min))
          (activate-mark)
          (call-interactively #'eudic-lookup-in-popup)))
      (with-temp-buffer
        (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "prompted")))
          (call-interactively #'eudic-lookup))))
    (should (equal (nreverse urls)
                   '("eudic://dict/hello" "eudic://lp-dict/hello%20world"
                     "eudic://dict/prompted")))))

(ert-deftest eudic-lookup-auto-add-is-optional-and-follows-open ()
  (dolist (command '(eudic-lookup eudic-lookup-in-popup))
    (let (events)
      (let ((eudic-open-url-function (lambda (_) (push 'open events))))
        (cl-letf (((symbol-function 'eudic--auto-add-word-to-studylist)
                   (lambda (word) (push word events))))
          (let ((eudic-auto-add-to-studylist nil))
            (funcall command "hello"))
          (should (equal events '(open)))
          (setq events nil)
          (let ((eudic-auto-add-to-studylist t))
            (funcall command " hello "))
          (should (equal (nreverse events) '(open "hello"))))))))

(ert-deftest eudic-lookup-open-failure-does-not-save ()
  (let ((eudic-auto-add-to-studylist t)
        (eudic-open-url-function (lambda (_) (error "Cannot open URL"))))
    (cl-letf (((symbol-function 'eudic--auto-add-word-to-studylist)
               (lambda (_) (ert-fail "Saved after failed launch"))))
      (should-error (eudic-lookup "hello")))))

(ert-deftest eudic-lookup-save-failure-keeps-lookup-and-reports-error ()
  (let ((eudic-auto-add-to-studylist t)
        opened notice)
    (let ((eudic-open-url-function (lambda (_) (setq opened t))))
      (cl-letf (((symbol-function 'eudic--auto-add-word-to-studylist)
                 (lambda (_) (error "Missing credentials")))
                ((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (setq notice (apply #'format format-string args)))))
        (eudic-lookup "hello")))
    (should opened)
    (should (string-match-p "Missing credentials" notice))))

(ert-deftest eudic-auto-add-sends-authenticated-json-asynchronously ()
  (let ((eudic-api-key "test-only-key")
        (eudic-api-host "https://example.invalid/api/open")
        (eudic-default-studylist-id "123")
        (eudic-default-language 'fr)
        request notice)
    (cl-letf (((symbol-function 'plz)
               (lambda (method url &rest args)
                 (setq request (list method url args)) 'fake-process)))
      (should (eq (eudic--auto-add-word-to-studylist " café ") 'fake-process)))
    (should (eq (car request) 'post))
    (should (equal (cadr request) "https://example.invalid/api/open/v1/studylist/words"))
    (let* ((args (nth 2 request))
           (body (json-parse-string (plist-get args :body) :object-type 'alist)))
      (should (equal (cdr (assoc-string "authorization" (plist-get args :headers) t))
                     "test-only-key"))
      (should (equal (alist-get 'language body) "fr"))
      (should (equal (alist-get 'category_id body) "123"))
      (should (equal (alist-get 'words body) ["café"]))
      (should (functionp (plist-get args :then)))
      (should (functionp (plist-get args :else)))
      ;; Run callbacks after the initiating call has returned.
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest values)
                   (setq notice (apply #'format format-string values)))))
        (funcall (plist-get args :then) nil)
        (should (string-match-p "saved café" notice))
        (funcall (plist-get args :else) nil)
        (should (string-match-p "could not save café" notice))))))

(ert-deftest eudic-auto-add-default-studylist ()
  (let ((eudic-api-key "test-only-key")
        (eudic-default-studylist-id "0")
        (eudic-default-language 'en)
        body)
    (cl-letf (((symbol-function 'plz)
               (lambda (_method _url &rest args)
                 (setq body (json-parse-string (plist-get args :body)
                                               :object-type 'alist)))))
      (eudic--auto-add-word-to-studylist "hello"))
    (should (equal (alist-get 'category_id body) "0"))
    (should (equal (alist-get 'language body) "en"))))

(ert-deftest eudic-auto-add-validates-configuration-before-network ()
  (let ((eudic-api-key "test-only-key")
        (eudic-default-studylist-id "0")
        (eudic-default-language 'en))
    (cl-letf (((symbol-function 'plz)
               (lambda (&rest _) (ert-fail "Unexpected network request"))))
      (dolist (key '(nil "" " \t"))
        (let ((eudic-api-key key))
          (should-error (eudic--auto-add-word-to-studylist "hello") :type 'user-error)))
      (let ((eudic-default-studylist-id ""))
        (should-error (eudic--auto-add-word-to-studylist "hello") :type 'user-error))
      (let ((eudic-default-language 'unknown))
        (should-error (eudic--auto-add-word-to-studylist "hello") :type 'user-error))
      (should-error (eudic--auto-add-word-to-studylist " ") :type 'user-error))))

(provide 'eudic-test)
;;; eudic-test.el ends here
