;;; eudic-test.el --- Lookup and studylist tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'eudic-studylist)

(ert-deftest eudic-lookup-encodes-both-url-schemes ()
  (let ((eudic-auto-add-to-studylist nil)
        urls)
    (let ((eudic-open-url-function (lambda (url) (push url urls))))
      (eudic-lookup "  hello world/?#&  ")
      (eudic-lookup-in-popup " café 中文 "))
    (should (equal (nreverse urls)
                   '("eudic://dict/hello%20world%2F%3F%23%26"
                     "eudic://lp-dict/caf%C3%A9%20%E4%B8%AD%E6%96%87")))))

(ert-deftest eudic-lookup-rejects-empty-input-before-side-effects ()
  (let ((eudic-auto-add-to-studylist t)
        (eudic-open-url-function (lambda (_) (ert-fail "Opened empty lookup"))))
    (cl-letf (((symbol-function 'eudic--auto-add-word-to-studylist)
               (lambda (_) (ert-fail "Saved empty word"))))
      (dolist (word '(nil "" " \n\t "))
        (should-error (eudic-lookup word) :type 'user-error)
        (should-error (eudic-lookup-in-popup word) :type 'user-error)))))

(ert-deftest eudic-lookup-interactive-input ()
  (let ((eudic-auto-add-to-studylist nil)
        urls)
    (let ((eudic-open-url-function (lambda (url) (push url urls))))
      (with-temp-buffer
        (insert "hello world")
        (goto-char 3)
        (call-interactively #'eudic-lookup)
        (let ((transient-mark-mode t))
          (goto-char (point-max))
          (set-mark (point-min))
          (activate-mark)
          (call-interactively #'eudic-lookup-in-popup)))
      (with-temp-buffer
        (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "prompted")))
          (call-interactively #'eudic-lookup))))
    (should (equal (nreverse urls)
                   '("eudic://dict/hello" "eudic://lp-dict/hello%20world"
                     "eudic://dict/prompted")))))

(ert-deftest eudic-lookup-auto-add-is-optional-and-follows-open ()
  (dolist (command '(eudic-lookup eudic-lookup-in-popup))
    (let (events)
      (let ((eudic-open-url-function (lambda (_) (push 'open events))))
        (cl-letf (((symbol-function 'eudic--auto-add-word-to-studylist)
                   (lambda (word) (push word events))))
          (let ((eudic-auto-add-to-studylist nil))
            (funcall command "hello"))
          (should (equal events '(open)))
          (setq events nil)
          (let ((eudic-auto-add-to-studylist t))
            (funcall command " hello "))
          (should (equal (nreverse events) '(open "hello"))))))))

(ert-deftest eudic-lookup-open-failure-does-not-save ()
  (let ((eudic-auto-add-to-studylist t)
        (eudic-open-url-function (lambda (_) (error "Cannot open URL"))))
    (cl-letf (((symbol-function 'eudic--auto-add-word-to-studylist)
               (lambda (_) (ert-fail "Saved after failed launch"))))
      (should-error (eudic-lookup "hello")))))

(ert-deftest eudic-lookup-save-failure-keeps-lookup-and-reports-error ()
  (let ((eudic-auto-add-to-studylist t)
        opened notice)
    (let ((eudic-open-url-function (lambda (_) (setq opened t))))
      (cl-letf (((symbol-function 'eudic--auto-add-word-to-studylist)
                 (lambda (_) (error "Missing credentials")))
                ((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (setq notice (apply #'format format-string args)))))
        (eudic-lookup "hello")))
    (should opened)
    (should (string-match-p "Missing credentials" notice))))

(ert-deftest eudic-auto-add-sends-authenticated-json-asynchronously ()
  (let ((eudic-api-key "test-only-key")
        (eudic-api-host "https://example.invalid/api/open")
        (eudic-default-studylist-id "123")
        (eudic-default-language 'fr)
        request notice)
    (cl-letf (((symbol-function 'plz)
               (lambda (method url &rest args)
                 (setq request (list method url args)) 'fake-process)))
      (should (eq (eudic--auto-add-word-to-studylist " café ") 'fake-process)))
    (should (eq (car request) 'post))
    (should (equal (cadr request) "https://example.invalid/api/open/v1/studylist/words"))
    (let* ((args (nth 2 request))
           (body (json-parse-string (plist-get args :body) :object-type 'alist)))
      (should (equal (cdr (assoc-string "authorization" (plist-get args :headers) t))
                     "test-only-key"))
      (should (equal (alist-get 'language body) "fr"))
      (should (equal (alist-get 'category_id body) "123"))
      (should (equal (alist-get 'words body) ["café"]))
      (should (functionp (plist-get args :then)))
      (should (functionp (plist-get args :else)))
      ;; Run callbacks after the initiating call has returned.
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest values)
                   (setq notice (apply #'format format-string values)))))
        (funcall (plist-get args :then) nil)
        (should (string-match-p "saved café" notice))
        (funcall (plist-get args :else) nil)
        (should (string-match-p "could not save café" notice))))))

(ert-deftest eudic-auto-add-default-studylist ()
  (let ((eudic-api-key "test-only-key")
        (eudic-default-studylist-id "0")
        (eudic-default-language 'en)
        body)
    (cl-letf (((symbol-function 'plz)
               (lambda (_method _url &rest args)
                 (setq body (json-parse-string (plist-get args :body)
                                               :object-type 'alist)))))
      (eudic--auto-add-word-to-studylist "hello"))
    (should (equal (alist-get 'category_id body) "0"))
    (should (equal (alist-get 'language body) "en"))))

(ert-deftest eudic-auto-add-validates-configuration-before-network ()
  (let ((eudic-api-key "test-only-key")
        (eudic-default-studylist-id "0")
        (eudic-default-language 'en))
    (cl-letf (((symbol-function 'plz)
               (lambda (&rest _) (ert-fail "Unexpected network request"))))
      (dolist (key '(nil "" " \t"))
        (let ((eudic-api-key key))
          (should-error (eudic--auto-add-word-to-studylist "hello") :type 'user-error)))
      (let ((eudic-default-studylist-id ""))
        (should-error (eudic--auto-add-word-to-studylist "hello") :type 'user-error))
      (let ((eudic-default-language 'unknown))
        (should-error (eudic--auto-add-word-to-studylist "hello") :type 'user-error))
      (should-error (eudic--auto-add-word-to-studylist " ") :type 'user-error))))

(ert-deftest eudic-background-lookup-passes-text-as-data-and-saves-on-success ()
  (let ((system-type 'darwin)
        (eudic-activate nil)
        (eudic-auto-add-to-studylist t)
        (eudic-open-url-function (lambda (_) (ert-fail "Unexpected URL lookup")))
        (word "café 中文 \"quote\" \\path\nend tell\ndo shell script \"false\"")
        args saved)
    (cl-letf (((symbol-function 'executable-find) (lambda (_) "/usr/bin/osascript"))
              ((symbol-function 'make-process)
               (lambda (&rest options) (setq args options) 'test-process))
              ((symbol-function 'eudic--auto-add-word-to-studylist)
               (lambda (text) (setq saved text)))
              ((symbol-function 'process-status) (lambda (_) 'exit))
              ((symbol-function 'process-exit-status) (lambda (_) 0)))
      (unwind-protect
          (progn
            (should (eq (eudic-lookup (concat " " word " ")) 'test-process))
            (should-not saved)
            (should (equal (plist-get args :command)
                           (list "/usr/bin/osascript" "-e" eudic--lookup-script "--" word)))
            (should-not (string-match-p (regexp-quote word) eudic--lookup-script))
            (funcall (plist-get args :sentinel) 'test-process "finished\n")
            (should (equal saved word))
            (should-not (buffer-live-p (plist-get args :buffer))))
        (when (buffer-live-p (plist-get args :buffer))
          (kill-buffer (plist-get args :buffer)))))))

(ert-deftest eudic-background-lookup-reports-script-failure-without-saving ()
  (let ((system-type 'darwin)
        (eudic-activate nil)
        (eudic-auto-add-to-studylist t)
        args notice)
    (cl-letf (((symbol-function 'executable-find) (lambda (_) "/usr/bin/osascript"))
              ((symbol-function 'make-process)
               (lambda (&rest options) (setq args options) 'test-process))
              ((symbol-function 'eudic--auto-add-word-to-studylist)
               (lambda (_) (ert-fail "Saved after failed script")))
              ((symbol-function 'process-status) (lambda (_) 'exit))
              ((symbol-function 'process-exit-status) (lambda (_) 1))
              ((symbol-function 'message)
               (lambda (fmt &rest values) (setq notice (apply #'format fmt values)))))
      (unwind-protect
          (progn
            (eudic-lookup "hello")
            (with-current-buffer (plist-get args :buffer)
              (insert "Not authorized to send Apple events (-1743)\n"))
            (funcall (plist-get args :sentinel) 'test-process "exited abnormally\n")
            (should (string-match-p "Eudic lookup failed:.*-1743" notice))
            (should-not (buffer-live-p (plist-get args :buffer))))
        (when (buffer-live-p (plist-get args :buffer))
          (kill-buffer (plist-get args :buffer)))))))

(ert-deftest eudic-background-lookup-rejects-unsupported-requests ()
  (let ((eudic-activate nil)
        (eudic-open-url-function (lambda (_) (ert-fail "Unexpected URL fallback"))))
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest _) (ert-fail "Unexpected process"))))
      (let ((system-type 'darwin))
        (should-error (eudic-lookup-in-popup "hello") :type 'user-error)
        (cl-letf (((symbol-function 'executable-find) (lambda (_) nil)))
          (should-error (eudic-lookup "hello") :type 'user-error)))
      (let ((system-type 'gnu/linux))
        (should-error (eudic-lookup "hello") :type 'user-error)))))

(ert-deftest eudic-background-lookup-cleans-up-after-launch-failure ()
  (let ((system-type 'darwin)
        (eudic-activate nil)
        (eudic-auto-add-to-studylist t)
        output)
    (cl-letf (((symbol-function 'executable-find) (lambda (_) "/usr/bin/osascript"))
              ((symbol-function 'make-process)
               (lambda (&rest args)
                 (setq output (plist-get args :buffer))
                 (error "Could not start osascript")))
              ((symbol-function 'eudic--auto-add-word-to-studylist)
               (lambda (_) (ert-fail "Saved after launch failure"))))
      (should-error (eudic-lookup "hello"))
      (should-not (buffer-live-p output)))))

(ert-deftest eudic-studylist-cache-listing-does-not-mutate-language-lists ()
  (let* ((english (make-eudic-studylist :id "en-1" :language 'en))
         (french (make-eudic-studylist :id "fr-1" :language 'fr))
         (eudic-studylists (list (list 'en english) (list 'fr french))))
    (dotimes (_ 2)
      (should (equal (eudic--studylists) (list english french))))
    (should (equal (alist-get 'en eudic-studylists) (list english)))
    (should (equal (alist-get 'fr eudic-studylists) (list french)))))

(ert-deftest eudic-studylist-refresh-clears-stale-cache ()
  (let ((eudic-studylists '((obsolete stale)))
        refreshed)
    (cl-letf (((symbol-function 'eudic--refresh-studylists)
               (lambda (language)
                 (should-not (alist-get 'obsolete eudic-studylists))
                 (push language refreshed))))
      (eudic-refresh-studylists))
    (should (equal (nreverse refreshed) '(en de es fr)))
    (should-not eudic-studylists)))

(ert-deftest eudic-studylist-symbol-language-and-cache-updates ()
  (let ((eudic-studylists nil)
        (studylist (eudic--make-studylist
                    '((id . "123") (language . "fr") (name . "French")))))
    (should (eq (eudic-studylist-language studylist) 'fr))
    (should (equal (eudic--studylist-identity-string studylist)
                   "Français/123/French"))
    (eudic--add-studylist-to-cache studylist)
    (should (equal (alist-get 'fr eudic-studylists) (list studylist)))
    (eudic--remove-studylist-from-cache studylist)
    (should-not (alist-get 'fr eudic-studylists))))

(ert-deftest eudic-manual-add-preserves-explicit-studylist-argument ()
  (let ((studylist (make-eudic-studylist :id "123" :language 'fr))
        saved)
    (cl-letf (((symbol-function 'eudic--add-word-to-studylist)
               (lambda (word target) (setq saved (list word target))))
              ((symbol-function 'eudic--default-studylist)
               (lambda () (ert-fail "Explicit studylist was ignored"))))
      (eudic-add-word-to-studylist "bonjour" studylist))
    (should (equal saved (list "bonjour" studylist)))))

(ert-deftest eudic-manual-add-preserves-default-studylist-settings ()
  (let* ((english (make-eudic-studylist :id "0" :language 'en))
         (french (make-eudic-studylist :id "0" :language 'fr))
         (custom (make-eudic-studylist :id "123" :language 'fr))
         (eudic-studylists (list (list 'en english) (list 'fr french custom)))
         (eudic-default-language 'fr)
         saved)
    (cl-letf (((symbol-function 'eudic--add-word-to-studylist)
               (lambda (word target) (setq saved (list word target))))
              ((symbol-function 'eudic--select-studylist-from-mini-buffer)
               (lambda () (ert-fail "Configured studylist was ignored"))))
      (let ((eudic-default-studylist "language-default"))
        (eudic-add-word-to-studylist "bonjour")
        (should (equal saved (list "bonjour" french))))
      (let ((eudic-default-studylist "123"))
        (eudic-add-word-to-studylist "salut")
        (should (equal saved (list "salut" custom)))))))

(ert-deftest eudic-manual-add-preserves-interactive-prompts ()
  (let ((eudic-default-studylist nil)
        (studylist (make-eudic-studylist :id "123" :language 'fr))
        selected prompted saved)
    (cl-letf (((symbol-function 'eudic--select-studylist-from-mini-buffer)
               (lambda () (setq selected t) studylist))
              ((symbol-function 'read-string)
               (lambda (&rest _) (setq prompted t) "bonjour"))
              ((symbol-function 'eudic--add-word-to-studylist)
               (lambda (word target) (setq saved (list word target)))))
      (call-interactively #'eudic-add-word-to-studylist))
    (should selected)
    (should prompted)
    (should (equal saved (list "bonjour" studylist)))))

(provide 'eudic-test)
;;; eudic-test.el ends here
